FROM node:22-bookworm AS frontend

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build


FROM dunglas/frankenphp:php8.3-bookworm

RUN install-php-extensions \
    pdo_pgsql \
    pgsql \
    intl \
    zip \
    pcntl

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . .

RUN composer install \
    --no-dev \
    --optimize-autoloader \
    --no-interaction

COPY --from=frontend /app/public/build /app/public/build

CMD ["sh", "-c", "php artisan config:cache && php artisan route:cache && php artisan view:cache && frankenphp php-server --root public --listen :${PORT:-80}"]